name: barcode_scanner
description: "A new Flutter project to use platform view with iOS: https://github.com/mikebuss/MTBBarcodeScanner and Android: https://github.com/dm77/barcodescanner"
version: 0.0.1
homepage: https://github.com/phucanh08/barcode_scanner
repository: https://github.com/phucanh08/barcode_scanner

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  protobuf: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.anhlp.barcode_scanner
        pluginClass: BarcodeScannerPlugin
      ios:
        pluginClass: BarcodeScannerPlugin
